test4/config/routes.rb
Rails.application.routes.draw do

  get 'report/index'

  get 'report/show'

  resources :authors do

  end

  resources :articles do

  end

  resources :tags do

  end

  root 'authors#index'

end

test4/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  has_many :articles_tags, dependent: :destroy
  has_many :tags, through: :articles_tags
  has_many :comments, dependent: :destroy
end

test4/app/models/articles_tag.rb
class ArticlesTag < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
end

test4/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
  has_many :comments
end

test4/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author
  belongs_to :article
end

test4/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :articles_tags
  has_many :articles, through: :articles_tags
end

test4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

test4/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.page(params[:page]).per(10).order('created_at DESC')
  end

  def show
    @article = Article.find(params[:id])
  end
end

test4/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.page(params[:page]).per(10)
  end

  def show
    @author = Author.find(params[:id])
  end
end

test4/app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  end

  def show
     render file: File.join(Rails.root, 'public', 'reports', params[:item])
  end
end

test4/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

test4/app/helpers/application_helper.rb
module ApplicationHelper
end

test4/app/helpers/articles_helper.rb
module ArticlesHelper
end

test4/app/helpers/authors_helper.rb
module AuthorsHelper
end

test4/app/helpers/report_helper.rb
module ReportHelper
end

test4/app/helpers/tags_helper.rb
module TagsHelper
end

test4/app/views/articles/index.html.erb
<h1>Список статей</h1>

<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<%= paginate @articles %>

test4/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.author.name %></p>
<p><%= @article.body %></p>

<ul>
    <% @article.tags.each do |tag| %>
      <li>
        <%= link_to tag.title, tag_path(tag) %>
      </li>
    <% end %>
</ul>

test4/app/views/authors/index.html.erb
<h1>Authors#index</h1>

<ul>
<% @authors.each do |author| %>
  <li>
    <%= link_to author.name, author_path(author) %>
  </li>
<% end %>
</ul>

<%= paginate @authors %>

test4/app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<p><%= @author.email %></p>
<p><%= @author.city %></p>
<p><%= @author.address %></p>
<p><%= @author.birthday %></p>


Статьи

<ul>
  <% @author.articles.order('created_at DESC').each do |article| %>
      <li><%= link_to article.title, article_path(article) %> [<% article.tags.each do |tag| %> <%= link_to tag.title %> <% end %>]</li>
  <% end %>
</ul>

test4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <ul>
    <li><%= link_to 'Список авторов', authors_path %></li>
    <li><%= link_to 'Список статей', articles_path %></li>
    <li><%= link_to 'Отчет', report_index_path %></li>
  </ul>
</header>
<%= yield %>

</body>
</html>

test4/app/views/report/index.html.erb
<h1>Report#index</h1>

<ul>
  <% Dir.foreach(File.join(Rails.root, 'public', 'reports')) do |item| %>
      <% next if item == '.' or item == '..' %>

      <li><%= link_to item, report_show_path(:item => item) %></li>
  <% end %>
</ul>

test4/app/views/report/show.html.erb
<h1>Report#show</h1>
<p>Find me in app/views/report/show.html.erb</p>

test4/app/views/tags/show.html.erb
<h1><%= @tag.title %></h1>
<ul>
  <% @tag.articles.order('created_at DESC').each do |article|  %>
      <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>